//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electionmvc.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ElectionDatabaseEntities1 : DbContext
    {
        public ElectionDatabaseEntities1()
            : base("name=ElectionDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAdaylar> tblAdaylars { get; set; }
        public virtual DbSet<tblKisiler> tblKisilers { get; set; }
        public virtual DbSet<tblPozisyon> tblPozisyons { get; set; }
        public virtual DbSet<tblPozisyonKisiler> tblPozisyonKisilers { get; set; }
        public virtual DbSet<tblSecim> tblSecims { get; set; }
        public virtual DbSet<tblSehirler> tblSehirlers { get; set; }
        public virtual DbSet<GecmisSecimler> GecmisSecimlers { get; set; }
        public virtual DbSet<GelecekSecimler> GelecekSecimlers { get; set; }
        public virtual DbSet<Secimler> Secimlers { get; set; }
    
        [DbFunction("ElectionDatabaseEntities1", "ALINANOYBILGISINIGETIR")]
        public virtual IQueryable<ALINANOYBILGISINIGETIR_Result> ALINANOYBILGISINIGETIR(Nullable<int> adayID)
        {
            var adayIDParameter = adayID.HasValue ?
                new ObjectParameter("adayID", adayID) :
                new ObjectParameter("adayID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ALINANOYBILGISINIGETIR_Result>("[ElectionDatabaseEntities1].[ALINANOYBILGISINIGETIR](@adayID)", adayIDParameter);
        }
    
        [DbFunction("ElectionDatabaseEntities1", "SECMENBILGISIGETIR")]
        public virtual IQueryable<SECMENBILGISIGETIR_Result> SECMENBILGISIGETIR(string tc)
        {
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SECMENBILGISIGETIR_Result>("[ElectionDatabaseEntities1].[SECMENBILGISIGETIR](@Tc)", tcParameter);
        }
    
        public virtual int secimSutunDoldur(string secimAd, Nullable<System.DateTime> secimTarihi, Nullable<System.DateTime> secimSonTarihi)
        {
            var secimAdParameter = secimAd != null ?
                new ObjectParameter("secimAd", secimAd) :
                new ObjectParameter("secimAd", typeof(string));
    
            var secimTarihiParameter = secimTarihi.HasValue ?
                new ObjectParameter("secimTarihi", secimTarihi) :
                new ObjectParameter("secimTarihi", typeof(System.DateTime));
    
            var secimSonTarihiParameter = secimSonTarihi.HasValue ?
                new ObjectParameter("secimSonTarihi", secimSonTarihi) :
                new ObjectParameter("secimSonTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("secimSutunDoldur", secimAdParameter, secimTarihiParameter, secimSonTarihiParameter);
        }
    
        public virtual int SP_AdaylikVer(string tc, Nullable<int> secimID)
        {
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AdaylikVer", tcParameter, secimIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_KisiBilgileriniDoldur(string ad, string soyad, string tc, Nullable<System.DateTime> dogumTarihi, string sifre, Nullable<int> sehirKod)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("Soyad", soyad) :
                new ObjectParameter("Soyad", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("DogumTarihi", dogumTarihi) :
                new ObjectParameter("DogumTarihi", typeof(System.DateTime));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("Sifre", sifre) :
                new ObjectParameter("Sifre", typeof(string));
    
            var sehirKodParameter = sehirKod.HasValue ?
                new ObjectParameter("SehirKod", sehirKod) :
                new ObjectParameter("SehirKod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KisiBilgileriniDoldur", adParameter, soyadParameter, tcParameter, dogumTarihiParameter, sifreParameter, sehirKodParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
