//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electionmvc.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdaylar
    {
        public int adayID { get; set; }
        public int secimID { get; set; }
        public int kisilerID { get; set; }
        public Nullable<int> AlinanOy { get; set; }
    
        public virtual tblKisiler tblKisiler { get; set; }
        public virtual tblSecim tblSecim { get; set; }
    }
}
