//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electionmvc.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKisiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKisiler()
        {
            this.tblAdaylars = new HashSet<tblAdaylar>();
            this.tblPozisyonKisilers = new HashSet<tblPozisyonKisiler>();
        }

        public int kisilerID { get; set; }

        [Required(ErrorMessage = "*Bu alan doldurulmak zorunda")]
        public string Ad { get; set; }

        [Required(ErrorMessage = "*Bu alan doldurulmak zorunda")]

        public string Soyad { get; set; }

        [MinLength(11, ErrorMessage = "En az 11 Haneli Olmak Zorunda"), MaxLength(11, ErrorMessage = "En Fazla 11 Haneli Olmak Zorunda")]
        [Range(10000000000, 99999999999, ErrorMessage = "Girilen TC Kimlik Numarasý Geçersiz")]
        [Required(ErrorMessage = "*Bu alan doldurulmak zorunda")]
        [DisplayName("TC Kimlik No:")]
        public string Tc { get; set; }

        [Required(ErrorMessage = "*Bu alan doldurulmak zorunda")]

        [DataType(DataType.Date)]
        public System.DateTime DogumTarihi { get; set; }

        [Required(ErrorMessage = "*Bu alan doldurulmak zorunda")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }

        public Nullable<int> SehirKod { get; set; }

        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdaylar> tblAdaylars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPozisyonKisiler> tblPozisyonKisilers { get; set; }
        public virtual tblSehirler tblSehirler { get; set; }
    }
}
